"""Generate the InstructionsCrafter Word template.

Writes a python-docx-template (docxtpl)-compatible .docx file at
backend/templates/instruction_template.docx.

The template provides these placeholders:
    {{ title }}              -- document title (top of page)
    {{ date }}               -- formatted generation date
    {%p for step in steps %} -- begin per-step block
        {{ loop.index }}     -- current step number (1, 2, 3, ...)
        {{ step.instruction }}
        {{ step.image }}     -- replaced with an InlineImage by docxtpl
        {{ step.caption }}
    {%p endfor %}            -- end per-step block

The team can later open the resulting .docx in Microsoft Word and
adjust fonts, colors, or spacing -- but the Jinja tags ({{ ... }} and
{%p ... %}) must be preserved or rendering will break.

Re-running this script overwrites any manual edits to the .docx, so
adjust the script (or stop using it) once the template is finalized.

Run from the project root:
    python backend/scripts/build_template.py
"""

from pathlib import Path

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "templates"
    / "instruction_template.docx"
)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    doc = Document()

    # Editorial Manual brand alignment. Colors match the extension's
    # design system so the generated document is recognizable as
    # InstructionsCrafter output rather than generic Word output.
    ACCENT = RGBColor(0x30, 0x80, 0xF8)  # popup/toolbar accent blue
    INK = RGBColor(0x15, 0x17, 0x1C)  # body text (bluish-black, not pure)
    MID = RGBColor(0x6E, 0x76, 0x84)  # secondary / footer text

    # Consolas (not Geist Mono) because every Windows/Mac Word install
    # has Consolas; Geist Mono is a Google Font that recipients almost
    # certainly don't have, and Word's font substitution would fall back
    # to a proportional font (Calibri), which would defeat the eyebrow.
    MONO_FONT = "Consolas"

    doc.styles["Title"].font.color.rgb = ACCENT
    doc.styles["Heading 2"].font.color.rgb = ACCENT
    doc.styles["Body Text"].font.color.rgb = INK
    doc.styles["Normal"].font.color.rgb = INK
    # Captions in mid-gray regular weight (still italic + centered from
    # the base style). Without this they ship bold italic accent-blue,
    # which competes with the STEP label for visual weight; mid-gray
    # makes them read as quieter "alt-text" descriptions.
    doc.styles["Caption"].font.color.rgb = MID
    doc.styles["Caption"].font.bold = False

    # Title's bottom border ships in the default Title style as Word's
    # generic blue. Replace it with the brand accent via direct XML
    # (python-docx has no high-level API for paragraph borders).
    title_pPr = doc.styles["Title"].element.get_or_add_pPr()
    for old in title_pPr.findall(qn("w:pBdr")):
        title_pPr.remove(old)
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")  # 6 eighth-points = 0.75 pt
    bottom.set(qn("w:space"), "4")
    bottom.set(qn("w:color"), "3080F8")
    pBdr.append(bottom)
    title_pPr.append(pBdr)

    # Page setup: A4 landscape with 0.635 cm (0.25 in) uniform margins.
    # Landscape orientation gives screenshots more horizontal room; the very
    # tight margins maximize content area for screen-only viewing (this
    # document is digital, not printed).
    section = doc.sections[0]
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width = Cm(29.7)
    section.page_height = Cm(21.0)
    section.top_margin = Cm(0.635)
    section.bottom_margin = Cm(0.635)
    section.left_margin = Cm(0.635)
    section.right_margin = Cm(0.635)

    # Brand footer on every page. Format:
    #     Generated by InstructionsCrafter · Page X of Y
    # Mono-caps mid-gray, centered, ~8pt. PAGE and NUMPAGES are Word
    # field codes evaluated at open time -- they don't need to be
    # known when the template is built.
    footer_p = section.footer.paragraphs[0]
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    def _styled_footer_run(text: str, no_proof: bool = False):
        run = footer_p.add_run(text)
        run.font.name = MONO_FONT
        run.font.size = Pt(8)
        run.font.color.rgb = MID
        if no_proof:
            run._element.get_or_add_rPr().append(OxmlElement("w:noProof"))
        return run

    def _add_page_field(instr: str):
        """Append a Word field (PAGE / NUMPAGES) run with the same
        mono-caps mid-gray styling as the surrounding footer text.
        Word re-evaluates the field on every open, so the displayed
        page number stays in sync as the document grows or shrinks."""
        run = _styled_footer_run("", no_proof=True)
        r_el = run._element
        fld_begin = OxmlElement("w:fldChar")
        fld_begin.set(qn("w:fldCharType"), "begin")
        r_el.append(fld_begin)
        instr_text = OxmlElement("w:instrText")
        instr_text.set(qn("xml:space"), "preserve")
        instr_text.text = instr
        r_el.append(instr_text)
        fld_end = OxmlElement("w:fldChar")
        fld_end.set(qn("w:fldCharType"), "end")
        r_el.append(fld_end)

    # "Generated by InstructionsCrafter " (with noProof on the brand
    # name run so recipients don't see a red squiggle).
    _styled_footer_run("Generated by InstructionsCrafter", no_proof=True)
    _styled_footer_run(" · Page ")
    _add_page_field("PAGE")
    _styled_footer_run(" of ")
    _add_page_field("NUMPAGES")

    # Title -- 24pt bold, centered (Title style).
    title_p = doc.add_paragraph(style=doc.styles["Title"])
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_p.add_run("{{ title }}")

    # Subtitle -- "GENERATED · MONTH DD, YYYY" in mono-caps mid-gray.
    # Overrides the Subtitle style's italic accent-blue serif with run-
    # level formatting so the date reads as the same meta-info eyebrow
    # used in the extension popup's "RECORDER" version label.
    # `{{ date|upper }}` uppercases the date string at render time
    # without changing document.py's strftime format.
    subtitle_p = doc.add_paragraph(style=doc.styles["Subtitle"])
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle_p.add_run("GENERATED · {{ date|upper }}")
    subtitle_run.font.name = MONO_FONT
    subtitle_run.font.size = Pt(11)
    subtitle_run.font.color.rgb = MID
    subtitle_run.font.italic = False

    # Optional Overview block -- wrapped in {%p if introduction %} so it
    # only renders when the AI-generated introduction is non-empty. On
    # rule-based-fallback runs the introduction is "" and the entire
    # block (heading + paragraph) disappears.
    doc.add_paragraph("{%p if introduction %}")

    overview_heading_p = doc.add_paragraph(style=doc.styles["Heading 2"])
    overview_heading_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    overview_heading_p.paragraph_format.keep_with_next = True
    overview_heading_p.add_run("Overview")

    intro_p = doc.add_paragraph(style=doc.styles["Body Text"])
    intro_p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    intro_p.paragraph_format.space_after = Pt(12)
    intro_p.add_run("{{ introduction }}")

    doc.add_paragraph("{%p endif %}")

    # For-loop opener -- {%p ... %} tells docxtpl to delete the entire
    # paragraph after processing, so no blank line appears in output.
    doc.add_paragraph("{%p for step in steps %}")

    # Step heading -- "STEP NN" mono-caps eyebrow that echoes the
    # extension popup's "RECORDER" version label. Uses Consolas at 11pt
    # regular weight (not the Heading 2 default sans-serif bold) to
    # give it the labelled-section feel rather than a heading feel.
    # `keep_with_next` glues the heading to the instruction so they
    # cannot be split across pages.
    heading_p = doc.add_paragraph(style=doc.styles["Heading 2"])
    heading_p.paragraph_format.keep_with_next = True
    heading_run = heading_p.add_run('STEP {{ "%02d"|format(loop.index) }}')
    heading_run.font.name = MONO_FONT
    heading_run.font.size = Pt(11)
    heading_run.font.bold = False

    # Instruction body -- justified, 12pt space-after (Body Text style).
    # `keep_with_next` glues the instruction to the image below.
    instruction_p = doc.add_paragraph(style=doc.styles["Body Text"])
    instruction_p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    instruction_p.paragraph_format.space_after = Pt(12)
    instruction_p.paragraph_format.keep_with_next = True
    instruction_p.add_run("{{ step.instruction }}")

    # Image placeholder -- centered. docxtpl replaces {{ step.image }} with
    # the InlineImage object passed in the rendering context.
    # `keep_with_next` glues the image to its caption.
    image_p = doc.add_paragraph()
    image_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    image_p.paragraph_format.keep_with_next = True
    image_p.add_run("{{ step.image }}")

    # Caption -- italic, centered (Caption style is italic by default).
    caption_p = doc.add_paragraph(style=doc.styles["Caption"])
    caption_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    caption_p.add_run("{{ step.caption }}")

    # Blank line for visual breathing room between steps.
    doc.add_paragraph()

    # For-loop closer.
    doc.add_paragraph("{%p endfor %}")

    doc.save(OUTPUT)
    print(f"Wrote: {OUTPUT}")
    print(f"Size:  {OUTPUT.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
